### ISSUE TITLE
Cuando se solapan 2 nodos los textos del nodo de abajo siguen apareciendo.

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#16]
![screen shot 2016-03-17 at 9 21 44 pm](https://cloud.githubusercontent.com/assets/7373873/13865137/f8ebe2ba-ec86-11e5-8a1f-f620d54ba213.png)

**Comment by MiliGaricoits** [comment]
fixed in 8b357077b436a2bd4ac15b1bf1c251b99e37efad, [[66dd6b0](https://github.com/MiliGaricoits/ofxComposer_nimp/commit/66dd6b0a6628d5e348bd28461a8325e901e36701)] and [[e4f4d76](https://github.com/MiliGaricoits/ofxComposer_nimp/commit/e4f4d76487835b3c3fc22998d12b67f4d8e6ca62)] for https://github.com/MiliGaricoits/ofxComposer_nimp.git
